### ISSUE TITLE
Add Datasette

### ISSUE THREAD

**Issue by yawaramin** [cube-js/awesome-tools#18]
From https://docs.datasette.io/en/latest/

> An open source multi-tool for exploring and publishing data
>
> Datasette is a tool for exploring and publishing data. It helps people take data of any shape or size and publish that as an interactive, explorable website and accompanying API.
>
> Datasette is aimed at data journalists, museum curators, archivists, local governments and anyone else who has data that they wish to share with the world. It is part of a wider ecosystem of tools and plugins dedicated to making working with structured data as productive as possible.

**Comment by igorlukanin** [comment]
Great idea!

https://github.com/simonw/datasette (5.2k stars)
