### ISSUE TITLE
Bug: FusionCharts tool preview layout is messy

### ISSUE THREAD

**Issue by alexandlazaris** [cube-js/awesome-tools#19]
**Browser**: Mac Firefox 88.0.1 (64-bit) 

**Expect**: Clean layout used by all other tools, e.g Google Charts
**Actual**: FusionCharts icon is super large, breaking its layout

https://awesome.cube.dev/

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/17981265/123622233-59783c00-d84f-11eb-954f-344776fe7ab4.png">

**Comment by igorlukanin** [comment]
Fixed in https://github.com/cube-js/awesome-tools/commit/fa889cbce23196dbb500ebd30af8088c1682febb.
