### ISSUE TITLE
Add P5js to the list

### ISSUE THREAD

**Issue by mckeeh3** [cube-js/awesome-tools#20]
[P5js](https://p5js.org/) would be a nice addition to the list.

I've used it to create some UIs, [here](https://github.com/mckeeh3/akka-typed-java-cluster-aware#the-cluster-dashboard) and [here](https://github.com/mckeeh3/woe-twin#woe-map-ui), in the past.

**Comment by igorlukanin** [comment]
Sounds great!

https://github.com/processing/p5.js (15.6k stars)
