### ISSUE TITLE
Selecting multiple tool types shows no results

### ISSUE THREAD

**Issue by RPisRyan** [cube-js/awesome-tools#27]
The tool type cards (Charting, Low-level) allow multi-selection, but appear to use AND logic, so no results show.

**Comment by igorlukanin** [comment]
Hi @RPisRyan 👋

You're right, the filter works as you described. It allows you to find tools that are able to do multiple types of visualizations ([example](https://awesome.cube.dev/?tools=3d&tools=maps)).

What would be the use case for the OR logic?

**Comment by RPisRyan** [comment]
I see your example. But almost all of the combinations produce no results. 
Until you have more tools with multiple categories, it would be less confusing if you limited to single-selection.
Feel free to close.

**Comment by igorlukanin** [comment]
Makes sense! We'll definitely be adding more tools down the road. Please feel free to open an issue for any additional tools that you'd like to be present here. Also, thanks for the feedback!
