### ISSUE TITLE
Add AntV/G2Plot?

### ISSUE THREAD

**Issue by visiky** [cube-js/awesome-tools#38]
**G2Plot** is an interactive and responsive charting library based on the grammar of graphics.

http://g2plot.antv.vision
https://github.com/antvis/G2Plot

Inactive?

last commit was in 2021: https://github.com/antvis/G2Plot/commits/develop
last release was in 2021: https://github.com/antvis/G2Plot/releases

**Comment by igorlukanin** [comment]
Added in #69. Thank you, @visiky!
