### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by stacksize** [cube-js/awesome-tools#78]
Hi guys,

am I free to fork this repo and rebuild it for a completely different purpose? 

Asking as I don't want to get in trouble down the road. Adding a link back to the original repo is not a problem.

**Comment by igorlukanin** [comment]
Hey Alex @stacksize 👋 

Thanks for the ping! I've just added the license file in [e25286a](https://github.com/cube-js/awesome-tools/commit/e25286a2c0bb2145b83f64f2c4ae8f7544be5675).

I've picked the MIT license, so definitely feel free to fork and rebuild this repo. Referencing us back would be really nice 😄 

By the way, what are you building? I'll be happy to learn more about that!
